# Generated by Django 4.2.11 on 2024-05-08 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0003_delete_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('quality_rating', models.FloatField(default=0)),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now)),
                ('acknowledgment_date', models.DateTimeField()),
                ('vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
