# Generated by Django 4.2.11 on 2024-05-08 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_rate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 8, 18, 32, 489673, tzinfo=datetime.timezone.utc)),
        ),
    ]
