# Generated by Django 4.2.11 on 2024-05-08 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_purchaseorder_order_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_rate',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 8, 19, 5, 585035, tzinfo=datetime.timezone.utc)),
        ),
    ]
